---
# Variable setup.
# - name: Include OS-specific variables.
#   include_vars: "{{ ansible_os_family }}.yml"

- name: Preflight
  ansible.builtin.include_tasks:
    file: check.yaml
  tags:
    - install
    - run

  # Setup/install tasks.
- name: run nuclei
  ansible.builtin.include_tasks:
    file: run.yaml
    apply:
      tags:
        - run
  tags: run

  # Setup/install tasks.
- name: split files
  ansible.builtin.include_tasks:
    file: split.yaml
    apply:
      tags:
        - split
  tags: split


- name: collect result files
  ansible.builtin.include_tasks:
    file: collect.yaml
    apply:
      tags:
        - collect
  tags: collect

- name: install nuclei linux
  ansible.builtin.include_tasks:
    file: setup-linuxAmd64.yaml
    apply:
      tags:
        - install
  tags: install
  when: ansible_os_family == 'Debian'

- name: install nuclei windows
  ansible.builtin.include_tasks:
    file: setup-winAmd64.yaml
    apply:
      tags:
        - install
  tags: install
  when: ansible_os_family == 'Windows'

- name: install nuclei windows
  ansible.builtin.include_tasks:
    file: setup-macAmd64.yaml
    apply:
      tags:
        - install
  tags: install
  when: ansible_os_family == 'MacOSX'
