---
# Variable setup.
# - name: Include OS-specific variables.
#   include_vars: "{{ ansible_os_family }}.yml"



  # Setup/install tasks.
- include_tasks: setup-linuxAmd64.yaml
  when: ansible_os_family == 'Debian'


- include_tasks: setup-winAmd64.yaml
  when: ansible_os_family == 'Windows'


- include_tasks: setup-macAmd64.yaml
  when: ansible_os_family == 'MacOSX'