
---

- name: Check if nuclei is installed
  ansible.builtin.command: nuclei --version
  register: nuclei_check
  failed_when: nuclei_check.rc != 0

- name: Run nuclei with custom arguments
  ansible.builtin.command: "{{ nuclei_command }}"
  vars:
    nuclei_command: "nuclei {{ nuclei_args }} -j -o /tmp/result.json"
  register: nuclei_run
  failed_when: nuclei_run.rc != 0

- debug:
    msg: "{{ nuclei_run.stdout | to_json }}"

- name: Read the content of a file
  set_fact:
    file_content: "{{ lookup('file', '/tmp/result.json') }}"

- name: Display the file content
  debug:
    msg: "{{ file_content }}"